os:
  - osx
  - linux
language: generic
osx_image: xcode11.3
dist: trusty
env:
  - SWIFT_VERSION=5.0
  - SWIFT_VERSION=5.1
  - SWIFT_VERSION=5.2
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - swift test

matrix:
  include:
    - os: osx
      language: swift
      osx_image: xcode11.3
      xcode_project: SwiftyPyString.xcodeproj
      script:
        - swift test
        - pod spec lint SwiftyPyString.podspec
