language: swift
osx_image: 
  - xcode10.3
  - xcode11
  - xcode11.1
  - xcode11.2
  - xcode11.3
xcode_project: SwiftyPyString.xcodeproj
script:
  - swift test
  - pod spec lint SwiftyPyString.podspec
