name: "Release with commit"

on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: ChanTsune/release-with-commit@v2.8.0
        with:
          regexp: "Release (\\d+([.]\\d+)*)\n*((\\s|\\S)+)"
          regexp_options: "us"
          release_name: "version $1"
          tag_name: "$1"
          body: "$3"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    outputs:
      created: ${{ steps.release.outputs.created }}
  publish:
    runs-on: macOS-latest
    needs: release
    if: ${{ needs.release.outputs.created == 'true' }}
    steps:
    - uses: actions/checkout@v3
    - name: Lint
      run: pod spec lint
    - name: Deploy
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: pod trunk push SwiftyPyString.podspec
